apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horiz-autoscale-fit-model
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fitmodel-module
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: rabbitmq_queue_messages_ready
      target:
        type: AverageValue
        averageValue: 5